import type { ProductRecordMap } from "./types";

const now = "2026-05-24T00:00:00.000Z";

export const fallbackProductData: {
  [Resource in keyof ProductRecordMap]: ProductRecordMap[Resource][];
} = {
  contract_opportunities: [
    {
      id: "contract-local-ai-services",
      title: "AI automation services opportunity",
      module: "contracts",
      status: "active",
      priority: "high",
      owner: "Murphree Enterprises LLC",
      due_at: "2026-06-14T21:00:00.000Z",
      tags: ["ai", "automation", "services", "technical-services"],
      notes: "Local fallback record for AI workflow and automation services.",
      metadata: {},
      created_at: now,
      updated_at: now,
      agency: "City Procurement",
      source: "local-fallback",
      source_url: "https://www.pittsburghpa.gov/Business-Development/Procurement",
      opportunity_number: "LOCAL-AI-001",
      value_estimate: 25000,
      fit_score: 92,
      deadline_at: "2026-06-14T21:00:00.000Z"
    },
    {
      id: "contract-local-web-app",
      title: "Website redesign and web application support",
      module: "contracts",
      status: "active",
      priority: "high",
      owner: "Murphree Enterprises LLC",
      due_at: "2026-06-21T21:00:00.000Z",
      tags: ["web", "website", "application", "software"],
      notes: "Website, portal, and app support opportunity.",
      metadata: {},
      created_at: now,
      updated_at: now,
      agency: "County Technology Office",
      source: "local-fallback",
      source_url: "https://www.emarketplace.state.pa.us/Search.aspx/Home.aspx",
      opportunity_number: "LOCAL-WEB-002",
      value_estimate: 60000,
      fit_score: 90,
      deadline_at: "2026-06-21T21:00:00.000Z"
    },
    {
      id: "contract-local-media",
      title: "Video production and digital media campaign",
      module: "contracts",
      status: "active",
      priority: "medium",
      owner: "Wolf Pacc Music Group LLC",
      due_at: "2026-06-27T21:00:00.000Z",
      tags: ["media", "video", "content", "creative"],
      notes: "Creative media, production, editing, and outreach support.",
      metadata: {},
      created_at: now,
      updated_at: now,
      agency: "Public Outreach Office",
      source: "local-fallback",
      source_url: "https://www.pittsburghpa.gov/Business-Development/Procurement",
      opportunity_number: "LOCAL-MEDIA-003",
      value_estimate: 40000,
      fit_score: 88,
      deadline_at: "2026-06-27T21:00:00.000Z"
    },
    {
      id: "contract-local-training",
      title: "AI tools training and staff enablement",
      module: "contracts",
      status: "active",
      priority: "medium",
      owner: "AI Wealth Empire",
      due_at: "2026-07-01T21:00:00.000Z",
      tags: ["ai", "training", "technical", "documentation"],
      notes: "Training, AI tool onboarding, documentation, and staff workflow support.",
      metadata: {},
      created_at: now,
      updated_at: now,
      agency: "Workforce Development Department",
      source: "local-fallback",
      source_url: "https://www.emarketplace.state.pa.us/Search.aspx/Home.aspx",
      opportunity_number: "LOCAL-TRAIN-004",
      value_estimate: 35000,
      fit_score: 86,
      deadline_at: "2026-07-01T21:00:00.000Z"
    },
    {
      id: "contract-local-data",
      title: "Data dashboard and reporting modernization",
      module: "contracts",
      status: "active",
      priority: "high",
      owner: "Murphree Enterprises LLC",
      due_at: "2026-07-09T21:00:00.000Z",
      tags: ["data", "analytics", "dashboard", "software"],
      notes: "Dashboard, reporting, analytics, and operational visibility opportunity.",
      metadata: {},
      created_at: now,
      updated_at: now,
      agency: "Public Data Office",
      source: "local-fallback",
      source_url: "https://sam.gov/content/opportunities",
      opportunity_number: "LOCAL-DATA-005",
      value_estimate: 80000,
      fit_score: 91,
      deadline_at: "2026-07-09T21:00:00.000Z"
    },
    {
      id: "contract-sled-facilities",
      title: "Facilities maintenance subcontracting support",
      module: "contracts",
      status: "active",
      priority: "medium",
      owner: "Murphree Enterprises LLC",
      due_at: "2026-07-15T21:00:00.000Z",
      tags: ["sled", "subcontracting", "facilities", "maintenance", "services"],
      notes: "SLED subcontracting target for maintenance, vendor support, and facility service partners.",
      metadata: {},
      created_at: now,
      updated_at: now,
      agency: "Regional School District",
      source: "local-fallback",
      source_url: "https://www.emarketplace.state.pa.us/Search.aspx/Home.aspx",
      opportunity_number: "SLED-FAC-006",
      value_estimate: 90000,
      fit_score: 62,
      deadline_at: "2026-07-15T21:00:00.000Z"
    },
    {
      id: "contract-sled-staffing",
      title: "Temporary staffing and administrative support",
      module: "contracts",
      status: "active",
      priority: "medium",
      owner: "Murphree Enterprises LLC",
      due_at: "2026-07-18T21:00:00.000Z",
      tags: ["sled", "subcontracting", "staffing", "admin", "services"],
      notes: "State/local administrative services opportunity with subcontracting potential.",
      metadata: {},
      created_at: now,
      updated_at: now,
      agency: "County Human Services",
      source: "local-fallback",
      source_url: "https://www.emarketplace.state.pa.us/Search.aspx/Home.aspx",
      opportunity_number: "SLED-STAFF-007",
      value_estimate: 55000,
      fit_score: 58,
      deadline_at: "2026-07-18T21:00:00.000Z"
    },
    {
      id: "contract-local-event-services",
      title: "Community event production and vendor services",
      module: "contracts",
      status: "active",
      priority: "medium",
      owner: "Wolf Pacc Music Group LLC",
      due_at: "2026-07-22T21:00:00.000Z",
      tags: ["sled", "events", "production", "media", "subcontracting"],
      notes: "Event services and production opportunity suitable for creative subcontracting.",
      metadata: {},
      created_at: now,
      updated_at: now,
      agency: "Parks and Recreation Department",
      source: "local-fallback",
      source_url: "https://www.pittsburghpa.gov/Business-Development/Procurement",
      opportunity_number: "LOCAL-EVENT-008",
      value_estimate: 65000,
      fit_score: 76,
      deadline_at: "2026-07-22T21:00:00.000Z"
    },
    {
      id: "contract-federal-subcontracting",
      title: "Federal prime subcontractor support services",
      module: "contracts",
      status: "active",
      priority: "high",
      owner: "Murphree Enterprises LLC",
      due_at: "2026-07-30T21:00:00.000Z",
      tags: ["federal", "subcontracting", "technical", "admin", "services"],
      notes: "Federal subcontracting target for teaming, technical support, documentation, and admin operations.",
      metadata: {},
      created_at: now,
      updated_at: now,
      agency: "Federal Prime Contractor",
      source: "local-fallback",
      source_url: "https://sam.gov/content/opportunities",
      opportunity_number: "FED-SUB-009",
      value_estimate: 150000,
      fit_score: 72,
      deadline_at: "2026-07-30T21:00:00.000Z"
    }
  ],
  content_assets: [
    {
      id: "content-ai-workflows-short",
      title: "AI workflow short-form campaign",
      module: "wealth",
      status: "queued",
      priority: "medium",
      owner: "AI Wealth Empire",
      due_at: null,
      tags: ["short-form", "ai", "lead-gen"],
      notes: "Seed asset for content workflow testing.",
      metadata: {},
      created_at: now,
      updated_at: now,
      platform: "TikTok",
      asset_type: "short_form",
      hook: "Stop doing manual business tasks.",
      call_to_action: "Book the AI workflow audit.",
      publish_at: null
    }
  ],
  wealth_leads: [],
  wealth_campaigns: [],
  audio_release_plans: [],
  beat_uploads: [],
  game_tasks: [],
  agent_runs: [],
  workflow_runs: [],
  command_notes: [],
  activity_events: []
};
